#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
LIBFRANKA_VERSION="${LIBFRANKA_VERSION:-${LIBFRANKA_DEFAULT_VERSION}}"

# Function to compare versions using sort -V
version_ge() {
    local version1="$1"
    local version2="$2"

    if [[ "$(printf "%s\n%s" "$version2" "$version1" | sort -V | head -n1)" == "$version2" ]]; then
        return 0  # version1 is greater than or equal to version2
    else
        return 1  # version1 is less than version2
    fi
}

"${SCRIPT_DIR}/install-poco"
if version_ge "$LIBFRANKA_VERSION" "0.14.0"; then
  "${SCRIPT_DIR}/install-pinocchio"
fi

echo "Installing libfranka version ${LIBFRANKA_VERSION}..."
TMP_DIR="$(mktemp -d /var/tmp/tmp.XXXXXXXXXX)"
git clone --recursive https://github.com/frankaemika/libfranka.git "${TMP_DIR}"
cd "${TMP_DIR}"

git checkout "${LIBFRANKA_VERSION}"

# Cherry-pick missing imports commit
git config user.email "john.doe@example.com"
git config user.name "John Doe"
if ! git merge-base --is-ancestor f1f46fb HEAD; then
  if git merge-base --is-ancestor 775160c HEAD; then
    git cherry-pick -m 1 f1f46fb;
  else
    sed -i '1i#include <stdexcept>' src/control_types.cpp
  fi
fi
git submodule update

mkdir build
cd build
# CMP0167 has to be set to OLD to be compatible with outdated boost versions
cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.10 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_POLICY_DEFAULT_CMP0167=OLD ..
make -j "$(nproc)"
sudo make install || make install

cd /
rm -rf "${TMP_DIR}"
echo "libfranka installed successfully"
