#!/bin/bash
set -e

echo "Installing POCO version ${POCO_VERSION}..."
TMP_DIR="$(mktemp -d /var/tmp/tmp.XXXXXXXXXX)"
git clone https://github.com/pocoproject/poco.git "${TMP_DIR}"
cd "${TMP_DIR}"
git checkout "${POCO_VERSION}"
mkdir build_
cd build_
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j "$(nproc)"
sudo make install || make install
cd /
rm -rf "${TMP_DIR}"
echo "POCO installed successfully"
