#!/bin/bash
set -e

echo "Installing Pinocchio version ${PINOCCHIO_VERSION}..."
TMP_DIR="$(mktemp -d /var/tmp/tmp.XXXXXXXXXX)"
git clone --recursive https://github.com/stack-of-tasks/pinocchio "${TMP_DIR}"
cd "${TMP_DIR}"
git checkout "${PINOCCHIO_VERSION}"
mkdir build
cd build
# CMP0167 has to be set to OLD to be compatible with outdated boost versions
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_DEFAULT_CMP0167=OLD -DBUILD_WITH_URDF_SUPPORT=on -DBUILD_PYTHON_INTERFACE=off -DBUILD_TESTING=off
make -j "$(nproc)"
sudo make install || make install
cd /
rm -rf "${TMP_DIR}"
echo "Pinocchio installed successfully"
